# Generated by Django 2.0 on 2020-04-26 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Category Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CategoryAndSubcategory.Category')),
            ],
        ),
    ]
