# Generated by Django 2.0 on 2020-04-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CategoryAndSubcategory', '0002_auto_20200426_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='updatedAt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
