# Generated by Django 2.0 on 2020-05-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BannerImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerImage', models.FileField(blank=True, null=True, upload_to='media/uploads/')),
                ('bannerDescription', models.TextField(blank=True, null=True)),
                ('bannerType', models.CharField(blank=True, choices=[('HomePage', 'HomePage'), ('TestPage', 'TestPage')], max_length=10, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrpTotal', models.FloatField(default=0.0)),
                ('aditionalDiscount', models.FloatField(default=0.0)),
                ('sampleCollectionCharges', models.FloatField(default=0.0)),
                ('deliveryCharges', models.FloatField(default=0.0)),
                ('totalAmount', models.FloatField(default=0.0)),
                ('totalSavings', models.FloatField(default=0.0)),
                ('minimunAmount', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('maxUsagePerUser', models.IntegerField(default=0)),
            ],
        ),
    ]
