# Generated by Django 2.0 on 2020-04-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Medicine Name')),
                ('actualPrice', models.FloatField(default=0.0, verbose_name='Actual Price (MRP)')),
                ('discountedPrice', models.FloatField(default=0.0, verbose_name='Price After Discount')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/uploads/')),
                ('testDescription', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='testIncluded',
            field=models.ManyToManyField(blank=True, null=True, to='DashBoard.Test'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='testRequirements',
            field=models.ManyToManyField(blank=True, null=True, to='DashBoard.sample'),
        ),
    ]
