# Generated by Django 2.0 on 2020-04-05 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='media/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicineName', models.CharField(blank=True, max_length=255, null=True)),
                ('manufaturerName', models.CharField(blank=True, max_length=255, null=True)),
                ('decsription', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('subCategory', models.CharField(blank=True, max_length=255, null=True)),
                ('batchNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('expiryDate', models.CharField(blank=True, max_length=255, null=True)),
                ('actualPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('discountedPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('rackNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('selfNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('gstTax', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(blank=True, max_length=255, null=True)),
                ('manufaturerName', models.CharField(blank=True, max_length=255, null=True)),
                ('decsription', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('subCategory', models.CharField(blank=True, max_length=255, null=True)),
                ('batchNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('expiryDate', models.CharField(blank=True, max_length=255, null=True)),
                ('actualPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('discountedPrice', models.CharField(blank=True, max_length=255, null=True)),
                ('rackNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('selfNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('gstTax', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('quantity', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='images',
            name='medicine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicieneImages', to='dashboard.Medicines'),
        ),
    ]
