# Generated by Django 2.0 on 2020-04-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
