# Generated by Django 2.0 on 2020-05-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0002_auto_20200425_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='minimumPayment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
