# Generated by Django 2.0 on 2020-05-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0003_labtest_minimumpayment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Labs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labName', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='packageOrSingle',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Package', 'Package')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='popularTest',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='labtest',
            name='testType',
            field=models.CharField(blank=True, choices=[('Pathology', 'Pathology'), ('Radiology', 'Radiology')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='labAvail',
            field=models.ManyToManyField(blank=True, null=True, to='DashBoard.Labs'),
        ),
    ]
