# Generated by Django 2.0 on 2020-04-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200405_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='actualPrice',
            field=models.FloatField(default=0.0, verbose_name='Actual Price (MRP)'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='batchNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Batch No.'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='decsription',
            field=models.TextField(blank=True, null=True, verbose_name='Medicine Description'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='discountedPrice',
            field=models.FloatField(default=0.0, verbose_name='Price After Discount'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='expiryDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry-Date'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='gstTax',
            field=models.IntegerField(default=0, verbose_name='GST/Other Tax'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufaturerName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='medicineName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Medicine Name'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='rackNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rack-Number'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='selfNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Self-Number'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='subCategory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='actualPrice',
            field=models.FloatField(default=0.0, verbose_name='Actual Price (MRP)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='batchNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Batch No.'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='decsription',
            field=models.TextField(blank=True, null=True, verbose_name='Medicine Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discountedPrice',
            field=models.FloatField(default=0.0, verbose_name='Price After Discount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='expiryDate',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry-Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='gstTax',
            field=models.IntegerField(default=0, verbose_name='GST/Other Tax'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufaturerName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Product Name'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='product',
            name='rackNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rack-Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='product',
            name='selfNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Self-Number'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sub-Category'),
        ),
    ]
