# Generated by Django 2.0 on 2020-04-05 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20200405_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category Name')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufaturerName', models.CharField(blank=True, max_length=255, null=True, verbose_name='Manufacturer Name')),
            ],
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCategoryName', models.CharField(blank=True, max_length=100, null=True, verbose_name='Sub Category Name')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Categorie')),
            ],
        ),
        migrations.AlterField(
            model_name='medicine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Categorie', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufaturerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SubCategorie', verbose_name='Sub Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Categorie', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufaturerName',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.SubCategorie', verbose_name='Sub Category'),
        ),
    ]
