# Generated by Django 2.0 on 2020-03-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugZoneUsers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deviceToken',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='deviceType',
            field=models.CharField(blank=True, choices=[('I', 'IOS'), ('A', 'ANDROID')], max_length=2, null=True),
        ),
    ]
