# Generated by Django 2.0 on 2020-03-30 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugZoneUsers', '0002_auto_20200328_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Admin'), ('2', 'Sub-Admin'), ('3', 'User')], max_length=2, null=True),
        ),
    ]
