# Generated by Django 2.0 on 2020-04-05 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugZoneUsers', '0005_auto_20200405_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'Sub-Admin'), ('2', 'Lab-Admin')], max_length=2, null=True),
        ),
    ]
