# Generated by Django 2.0 on 2020-04-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugZoneUsers', '0006_auto_20200405_1700'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactus',
            options={'verbose_name_plural': 'Contact Us'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='otpVerified',
            field=models.BooleanField(default=False),
        ),
    ]
