# Generated by Django 2.0 on 2020-05-01 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugZoneUsers', '0007_auto_20200409_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uploadDocument',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
