# Generated by Django 2.0 on 2020-05-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugZoneUsers', '0008_customuser_uploaddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=8, null=True),
        ),
    ]
