# Generated by Django 2.0 on 2020-04-26 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorConsultation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorconsultancy',
            name='consultationFee',
        ),
        migrations.AddField(
            model_name='doctorlist',
            name='consultationFee',
            field=models.FloatField(default=0.0),
        ),
    ]
