# Generated by Django 2.0 on 2020-05-01 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorConsultation', '0002_auto_20200426_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorlist',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorlist',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='doctorlist',
            name='uploadDocument',
            field=models.FileField(blank=True, null=True, upload_to='media/uploads/'),
        ),
    ]
