# Generated by Django 2.0 on 2020-05-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prescription', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadprescription',
            old_name='medicineName',
            new_name='medicinesDescription',
        ),
        migrations.RemoveField(
            model_name='uploadprescription',
            name='gender',
        ),
    ]
